language: rust
rust:
  - 1.32.0
install:
  - rustup toolchain install nightly-2018-12-06
  - rustup component add rustfmt-preview --toolchain nightly-2018-12-06
  - rustup component add clippy-preview --toolchain nightly-2018-12-06
before_script:
  - cargo fetch --verbose
script:
  - cargo +nightly-2018-12-06 fmt -- --check
    && RUST_BACKTRACE=1 cargo test --verbose --all
    && cargo +nightly-2018-12-06 clippy --all --all-targets -- -D warnings
matrix:
  include:
    - os: linux
    - os: osx
cache:
  cargo: true
  directories:
    - "$HOME/.rustup"
    - "$HOME/.cache/yarn"
    - "$TRAVIS_BUILD_DIR/test/node_modules"
before_cache:
  - rm -rf $HOME/.cargo/registry
  - rm -rf $TRAVIS_BUILD_DIR/target

git:
  depth: 1
